### ISSUE TITLE
Relic filtering issues [needs investigation]

### ISSUE THREAD

**Issue by casey-c** [casey-c/FilterTheSpire#35]
Got a bug report from a steam user:

```
Hiro [2023-01-09]

Great Mod!
However, it seems that this mod currently does not have a relic filter functioning well.
Even if I try to get ice cream by sacrificing HP in a deal with Neo, I get another random relic.
I am playing in Japanese.
No extra mods included.
```

This could have a number of different causes:
* Relic filter itself could be buggy
* Insufficient documentation (user is expecting different behavior based on our UI, and doing something they believe "should work" and having it do something else; note that this could also be a translation barrier as well and perhaps our English instructions are being misinterpreted)
* Some back-end localization issue with the game language being in Japanese instead of English (extremely unlikely since our code is *probably* localization agnostic - but it doesn't hurt to check this just in case)

We'll have to do a deeper examination into what's happening here to hopefully figure out what went wrong and to see if we can help them.

I'm going to leave a comment on Steam to see if I can get any further details and point them to this thread just in case.

**Comment by MH1r0** [comment]
Thank you for your kindness!!
First of all, I'm not good at English.
Sorry if there is any rudeness.

I reinstalled the game and reset the save.
After that, I tried "Filter the Spire".
Neow's options and merchant relic filters worked perfectly. (wonderful!)

However, when I trade HP for a rare relic in Neo's option, I get a random relic instead of the only ice cream of my choice. (Since only rare relics are selected, I think the filter itself is working)

Next, I selected "transform card" in the filter.
Then the option itself will always appear, but it will be a random one instead of the one I chose.
My filter selection is partially working.

Finally, I will send you my screenshot and the contents of the "Filter the Spire" configuration file that was in "Mod the Spire".

Thank you very much for your prompt response!

#Tue Jan 10 17:34:41 JST 2023
filters={"activeFilters"\:{"NthBossRelic"\:{"filterType"\:"NthBossRelic","possibleValues"\:[],"secondaryValues"\:[],"possibleEncounterIndices"\:[0],"searchCards"\:{}},"NeowBonus"\:{"filterType"\:"NeowBonus","possibleValues"\:["ONE_RARE_RELIC"],"secondaryValues"\:["PERCENT_DAMAGE"],"possibleEncounterIndices"\:[0],"searchCards"\:{}},"NthShopRelic"\:{"filterType"\:"NthShopRelic","possibleValues"\:["Membership Card"],"secondaryValues"\:[],"possibleEncounterIndices"\:[0],"searchCards"\:{}},"NthRelic"\:{"filterType"\:"NthRelic","possibleValues"\:["Ice Cream"],"secondaryValues"\:[],"possibleEncounterIndices"\:[0],"searchCards"\:{}}}}
allNeowBonuses=true

![Modded Slay the Spire 2023_01_10 17_34_00](https://user-images.githubusercontent.com/122350622/211506893-1311c24b-8b8a-40aa-b238-b0da563f8ccf.png)
![Modded Slay the Spire 2023_01_10 17_34_22](https://user-images.githubusercontent.com/122350622/211506899-30ea0077-e31f-4d62-9f43-18a65f423bc8.png)
![Modded Slay the Spire 2023_01_10 17_34_27](https://user-images.githubusercontent.com/122350622/211506908-cb3c8f3b-ef7d-482b-bd5a-e9a3141406c8.png)
![Modded Slay the Spire 2023_01_10 17_34_35](https://user-images.githubusercontent.com/122350622/211506911-128a09e4-60cc-4c6e-a393-033b9dda8714.png)
![Modded Slay the Spire 2023_01_10 17_34_43](https://user-images.githubusercontent.com/122350622/211506915-167b45df-3ebf-4b46-9341-a30b33b3b956.png)
![Modded Slay the Spire 2023_01_10 17_36_19](https://user-images.githubusercontent.com/122350622/211506918-d8323a24-c45d-448b-9773-54b10df10925.png)
![Modded Slay the Spire 2023_01_10 17_36_22](https://user-images.githubusercontent.com/122350622/211506927-98a6ea0d-ea2a-41dc-9c75-cdc14de9d01f.png)
![ModTheSpire 3 30 0 2023_01_10 17_33_15](https://user-images.githubusercontent.com/122350622/211506943-732ed818-40b0-45d6-81a6-72fee837b848.png)

**Comment by brianyee** [comment]
hello @MH1r0!

Thanks so much for the detailed comment. Do you have everything unlocked? This mod assumes you have everything unlocked by leveling up your characters. Ice cream is unlocked by default, but there are a total of 5 Rare relics that are unlockable that can mess up the RNG if they are not available.

**Comment by MH1r0** [comment]
I'm sorry!
Clearly, I thought it had nothing to do with things that were lifted from the beginning.

Is it the same for "Card Transformation"?

If so, should I clear all characters multiple times to unlock them before using Filter of the Spire?

**Comment by MH1r0** [comment]
I installed "UnlockEverythingMod" as a trial.

And "Filter the Spire" definitely brought us ice cream!
(I tried it with each of the 4 characters!)

It was the perfect solution!

I'm playing StS for "Filter the Spire"!

Thank you very much!

**Comment by brianyee** [comment]
Great! Glad you were able to solve it. Have fun!
