### ISSUE TITLE
FilterTheSpire is not compatible with "Battle Towers" mod

### ISSUE THREAD

**Issue by seowth** [casey-c/FilterTheSpire#36]
Dear casey-c,

I was having some issues getting my desired Neow Bonuses to show up then I realized [Filter The Spire](https://steamcommunity.com/sharedfiles/filedetails/?id=2279130265&searchtext=filter) is not compatible with [Battle Towers](https://steamcommunity.com/sharedfiles/filedetails/?id=2724117330&searchtext=battle+tower).

This was my journey:-

1.  Based on these settings... (+ installing [this unlock everything mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1614230369&searchtext=unlock) to be sure [that it wasn't the same as someone else's issue])

![20230116070922_1](https://user-images.githubusercontent.com/87141050/212688868-c26b76f3-bd2a-4b05-b599-ffa77982d632.jpg)

+

![20230116070924_1](https://user-images.githubusercontent.com/87141050/212689014-37baa11b-60c3-44a4-9a5f-75081431aafb.jpg)

+

![20230116070926_1](https://user-images.githubusercontent.com/87141050/212689113-d71ba9e3-a1e9-4397-ae0c-0fa753f31bb8.jpg)

+

![20230116070929_1](https://user-images.githubusercontent.com/87141050/212689141-8ece8407-a766-4bed-af0a-7ffce3eaac58.jpg)

+

![20230116070932_1](https://user-images.githubusercontent.com/87141050/212696864-8883d571-3b33-4e5f-92be-4ab13cf867d6.jpg)

+

![20230116070934_1](https://user-images.githubusercontent.com/87141050/212696918-137c92b3-60e6-455b-938c-ffe570f7c11a.jpg)

+

![20230116070936_1](https://user-images.githubusercontent.com/87141050/212696992-98511c3f-9902-4e4e-8050-8d78693c6a13.jpg)

+ [Proof of unlock all]

![20230116065546_1](https://user-images.githubusercontent.com/87141050/212689345-ec1f59e1-6d2c-42cc-8b4c-29ca11096874.jpg)

+

![20230116071034_1](https://user-images.githubusercontent.com/87141050/212689538-8baeea92-2d58-4cec-b00a-3140db51fb08.jpg)

2. ...I kept getting these 2 specific cards when I exchanged max HP for 2x transform cards:  

+ [Power Through] + [Havoc] ...NOT the desired... [Whirlwind]+[Shrug it Off]

![20230116070812_1](https://user-images.githubusercontent.com/87141050/212690006-998970a0-f1e2-4d3f-886e-00c1b0a83906.jpg)

3: **After DISABLING BATTLE TOWERS**: 

![20230116071520_1](https://user-images.githubusercontent.com/87141050/212690183-d31f4b91-5ab2-4707-a183-c3f5e1b26c9e.jpg)

+

![20230116071525_1](https://user-images.githubusercontent.com/87141050/212690245-da380a85-4868-4c37-9164-872ed7e362b1.jpg)

+ **"FIXED" BY DISABLING BATTLE TOWERS**

![20230116071529_1](https://user-images.githubusercontent.com/87141050/212697395-98e2b683-aac1-4033-9306-0b2949e8df8d.jpg)

+

[EDIT]Modlist: Tested with just the two mods.

+ With Battle Towers; BUGGED - [Power Through] + [Havoc] 

![20230116145353_1](https://user-images.githubusercontent.com/87141050/212765155-d142a606-eb63-4356-ba22-8a40b8045d1d.jpg)

+ [EDIT] Without Battle Towers; Correctly [Whirlwind]+[Shrug it Off]

![20230116145616_1](https://user-images.githubusercontent.com/87141050/212765262-df47ea61-ddbe-4691-bc67-4b13e9e1a396.jpg)

**_Thanks for reading!_**

Is this something I should be bringing up with Battle Towers?
- BT adds "25 new relics"...and..."10+ new cards" & other expansion-like features but I'm assuming the main culprit messing something up with FTS is BT's relics & cards(?)
- BT replaces the chest nodes in the MIDDLE of Act 2 so the new BT nodes might not be the issue (?);
> Am I mistaken re: FTS' filters and options only having effect up to the reward of the Act 1 Boss(?) 

The FTS mod seems very(!) useful when functioning.

**Comment by brianyee** [comment]
so what was the fix, just so we can note it?

**Comment by seowth** [comment]
> so what was the fix, just so we can note it?

My apologies, there was no real fix, only that disabling Battle Towers makes FTS work properly again.

I wanted to flag the incompatibility to you devs and other users in case it ever comes up. 
Since there's no real error/ stack trace it's hard to document.

Also hoping there might be a patch in the future for them.

**Comment by brianyee** [comment]
I've been looking at the BattleTowers repo and can't find anything that would directly interfere with Filter the Spire (though it'd be a lot easier if I just installed BattleTowers and debugged directly)

Maybe I'll take a look, but it's not always too straightforward to add compatibility to a mod without adding a dependency

**Comment by seowth** [comment]
Would you mind directing me to the BT repo? I could not find a link on the Workshop page (neither in the Bug reports section) but I'm considering mentioning this bug & linking them over to this issue here.

I could also just mention it in the Bug Reports section of the Workshop directly.

**Comment by brianyee** [comment]
https://github.com/erasels/MtSAnniversary-BattleTowers

**Comment by erasels** [comment]
Hey, that's a pretty thorough explanation of your findings, thanks for that. Looking at the neow card transofrmation code
`AbstractDungeon.transformCard(AbstractDungeon.gridSelectScreen.selectedCards.get(0), false, NeowEvent.rng);`
Where NeowEvent.rng is a new random instance with the run seed, I'm quite confused as to how this could've been influenced by battle towers.

The only thing I can even begin to guess at would be that our save field modifications (to keep track of where you are in the tower on save load) interferes somehow but looking through the code, I don't see anything that makes me suspcious.
https://github.com/erasels/MtSAnniversary-BattleTowers/tree/main/BattleTowers/src/main/java/BattleTowers/patches/saveload

I don't exactly understand how this mod works, so there could definitely be something I missed but I went through all our random calls and none of them should impact the run's RNG by the Neow room

**Comment by brianyee** [comment]
I half figured it out. The issue is not the RNG, with or without Battle Towers, the RNG counter is 7 when it gets both transforms. However, when it gets the transforms, the lists are different in `returnTrulyRandomCardFromAvailable` when Battle Towers is enabled vs disabled

Here are the card lists:

### FtS/vanilla
[Anger, Cleave, Warcry, Flex, Iron Wave, Body Slam, True Grit, Shrug It Off, Clash, Thunderclap, Pommel Strike, Twin Strike, Clothesline, Armaments, Havoc, Headbutt, Wild Strike, Heavy Blade, Perfected Strike, Sword Boomerang, Evolve, Uppercut, Ghostly Armor, Fire Breathing, Dropkick, Carnage, Bloodletting, Rupture, Second Wind, Searing Blow, Battle Trance, Sentinel, Entrench, Rage, Feel No Pain, Disarm, Seeing Red, Dark Embrace, Combust, Whirlwind, Sever Soul, Rampage, Shockwave, Metallicize, Burning Pact, Pummel, Flame Barrier, Blood for Blood, Intimidate, Hemokinesis, Reckless Charge, Infernal Blade, Dual Wield, Power Through, Inflame, Spot Weakness, Double Tap, Demon Form, Bludgeon, Feed, Limit Break, Corruption, Barricade, Fiend Fire, Berserk, Impervious, Juggernaut, Brutality, Reaper, Exhume, Offering, Immolate]

### Battle Towers
[Anger, Cleave, Warcry, Flex, Iron Wave, Shrug It Off, Armaments, Havoc, Headbutt, Wild Strike, Perfected Strike, Sword Boomerang, Body Slam, True Grit, Clash, Thunderclap, Pommel Strike, Twin Strike, Clothesline, Heavy Blade, Ghostly Armor, Fire Breathing, Dropkick, Carnage, Rupture, Second Wind, Searing Blow, Sentinel, Entrench, Rage, Dark Embrace, Whirlwind, Sever Soul, Rampage, Metallicize, Pummel, Blood for Blood, Hemokinesis, Reckless Charge, Power Through, Inflame, Evolve, Uppercut, Bloodletting, Battle Trance, Feel No Pain, Disarm, Seeing Red, Combust, Shockwave, Burning Pact, Flame Barrier, Intimidate, Infernal Blade, Dual Wield, Spot Weakness, Double Tap, Demon Form, Fiend Fire, Berserk, Impervious, Juggernaut, Brutality, Exhume, Offering, Bludgeon, Feed, Limit Break, Corruption, Barricade, Reaper, Immolate]

So the index that Shrug It Off would be in vanilla, Battle Towers has it as Havoc. I did a quick look through the code of BattleTowers but wasn't able to find how the card pools were being generated in a different order.

**Comment by seowth** [comment]
brianyee, that completely makes sense, I speculated the problem had something to do with the new cards from BT being added to the pool and it does feel like it operates in a consistent manner as per your description: 

> So the index that Shrug It Off would be in vanilla, Battle Towers has it as Havoc. I did a quick look through the code of BattleTowers but wasn't able to find how the card pools were being generated in a different order.
